{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kronos.fullname" . }}-backend
  namespace: kronos
  labels:
    {{- include "kronos.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kronos.backend.selectorLabels" . | nindent 6 }}
{{- end }}
