"""baseline schema

Revision ID: 56c861716f8f
Revises:
Create Date: 2026-08-10 14:01:12.552005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56c861716f8f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("hostname_lower", sa.String(length=255), nullable=False),
        sa.Column("criticality", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("environment", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("asset_id"),
        sa.UniqueConstraint("org_id", "hostname_lower", name="uq_assets_org_hostname"),
    )
    op.create_index(op.f("ix_assets_org_id"), "assets", ["org_id"], unique=False)
    op.create_table(
        "audit_anchor",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=True),
        sa.Column("anchor_date", sa.Date(), nullable=False),
        sa.Column("root_hash", sa.String(length=64), nullable=False),
        sa.Column("tsa_token", sa.LargeBinary(), nullable=True),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "anchor_date", name="uq_audit_anchor_org_date"),
    )
    op.create_index(
        op.f("ix_audit_anchor_anchor_date"), "audit_anchor", ["anchor_date"], unique=False
    )
    op.create_index(op.f("ix_audit_anchor_org_id"), "audit_anchor", ["org_id"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_username", sa.String(length=256), nullable=True),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("evidence_id", sa.UUID(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), nullable=False),
        sa.Column("prev_row_hash", sa.String(length=64), nullable=True),
        sa.Column("row_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("org_id", "sequence_number", name="uq_audit_log_org_seq"),
    )
    op.create_index(op.f("ix_audit_log_case_id"), "audit_log", ["case_id"], unique=False)
    op.create_index(op.f("ix_audit_log_evidence_id"), "audit_log", ["evidence_id"], unique=False)
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "cases",
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("org_alias", sa.String(length=128), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_number", sa.String(length=255), nullable=True),
        sa.Column(
            "classification", sa.String(length=64), server_default="UNCLASSIFIED", nullable=False
        ),
        sa.Column("status", sa.String(length=32), server_default="open", nullable=False),
        sa.Column("member_user_ids", sa.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("case_id"),
    )
    op.create_index(op.f("ix_cases_org_id"), "cases", ["org_id"], unique=False)
    op.create_table(
        "dead_letter_events",
        sa.Column("dead_letter_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(length=256), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("event_offset", sa.Integer(), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("error_type", sa.String(length=256), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("dead_lettered_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("dead_letter_id"),
    )
    op.create_index(
        op.f("ix_dead_letter_events_batch_id"), "dead_letter_events", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_dead_letter_events_org_id"), "dead_letter_events", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_dead_letter_events_source_id"), "dead_letter_events", ["source_id"], unique=False
    )
    op.create_table(
        "detection_correlations",
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("detection_id_a", sa.UUID(), nullable=False),
        sa.Column("detection_id_b", sa.UUID(), nullable=False),
        sa.Column("finding_id_a", sa.String(length=128), nullable=False),
        sa.Column("finding_id_b", sa.String(length=128), nullable=False),
        sa.Column("rule_ids", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("synced_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("correlation_id"),
    )
    op.create_index(
        op.f("ix_detection_correlations_detection_id_a"),
        "detection_correlations",
        ["detection_id_a"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detection_correlations_detection_id_b"),
        "detection_correlations",
        ["detection_id_b"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detection_correlations_org_id"), "detection_correlations", ["org_id"], unique=False
    )
    op.create_table(
        "detections",
        sa.Column("detection_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("org_alias", sa.String(length=128), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=True),
        sa.Column("finding_id", sa.String(length=128), nullable=False),
        sa.Column("detector_name", sa.String(length=256), nullable=False),
        sa.Column("source_index", sa.String(length=512), nullable=False),
        sa.Column("rule_matches", sa.JSON(), nullable=False),
        sa.Column("matched_document_ids", sa.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("finding_timestamp", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("triage_state", sa.String(length=32), server_default="NEW", nullable=False),
        sa.Column("synced_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("risk_factors", sa.JSON(), nullable=False),
        sa.Column("external_ticket_id", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("detection_id"),
        sa.UniqueConstraint("org_id", "finding_id", name="uq_detections_org_finding"),
    )
    op.create_index(op.f("ix_detections_case_id"), "detections", ["case_id"], unique=False)
    op.create_index(op.f("ix_detections_org_id"), "detections", ["org_id"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("org_alias", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("original_filename", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uploader_user_id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("md5", sa.String(length=32), nullable=True),
        sa.Column("minio_quarantine_key", sa.Text(), nullable=True),
        sa.Column("minio_evidence_key", sa.Text(), nullable=True),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.Column("client_declared_sha256", sa.String(length=64), nullable=True),
        sa.Column("legal_hold", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("object_lock_until", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("rfc3161_token", sa.LargeBinary(), nullable=True),
        sa.Column("quota_held", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index(op.f("ix_evidence_case_id"), "evidence", ["case_id"], unique=False)
    op.create_index(op.f("ix_evidence_org_id"), "evidence", ["org_id"], unique=False)
    op.create_table(
        "integration_source_cursors",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("cursor_value", sa.String(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("org_id", "source_id"),
    )
    op.create_table(
        "ioc_feed_current_indicators",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("feed_name", sa.String(length=256), nullable=False),
        sa.Column("ioc_type", sa.String(length=16), nullable=False),
        sa.Column("value_normalized", sa.String(length=512), nullable=False),
        sa.Column("indicator_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ioc_current_match",
        "ioc_feed_current_indicators",
        ["org_id", "ioc_type", "value_normalized"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ioc_feed_current_indicators_feed_id"),
        "ioc_feed_current_indicators",
        ["feed_id"],
        unique=False,
    )
    op.create_table(
        "ioc_feed_versions",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_format", sa.String(length=32), nullable=False),
        sa.Column("indicators", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("feed_id", "version", name="pk_ioc_feed_versions"),
    )
    op.create_index(
        op.f("ix_ioc_feed_versions_feed_id"), "ioc_feed_versions", ["feed_id"], unique=False
    )
    op.create_index(
        op.f("ix_ioc_feed_versions_org_id"), "ioc_feed_versions", ["org_id"], unique=False
    )
    op.create_table(
        "ioc_feeds",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("feed_id"),
        sa.UniqueConstraint("org_id", "name", name="uq_ioc_feeds_org_name"),
    )
    op.create_index(op.f("ix_ioc_feeds_org_id"), "ioc_feeds", ["org_id"], unique=False)
    op.create_table(
        "org_quotas",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("storage_quota_bytes", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("org_id"),
    )
    op.create_table(
        "published_custom_rules",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("opensearch_rule_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_index(
        op.f("ix_published_custom_rules_org_id"), "published_custom_rules", ["org_id"], unique=False
    )
    op.create_table(
        "rule_pack_versions",
        sa.Column("pack_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pack_id", "version", name="pk_rule_pack_versions"),
    )
    op.create_index(
        op.f("ix_rule_pack_versions_org_id"), "rule_pack_versions", ["org_id"], unique=False
    )
    op.create_index(
        op.f("ix_rule_pack_versions_pack_id"), "rule_pack_versions", ["pack_id"], unique=False
    )
    op.create_table(
        "rule_packs",
        sa.Column("pack_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pack_id"),
        sa.UniqueConstraint("org_id", "name", name="uq_rule_packs_org_name"),
    )
    op.create_index(op.f("ix_rule_packs_org_id"), "rule_packs", ["org_id"], unique=False)
    op.create_table(
        "sealed_batches",
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.String(length=256), nullable=False),
        sa.Column("sealed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("leaf_hashes", sa.JSON(), nullable=False),
        sa.Column("message_ids", sa.JSON(), nullable=False),
        sa.Column("merkle_root", sa.String(length=64), nullable=False),
        sa.Column("worm_bucket", sa.String(length=256), nullable=False),
        sa.Column("worm_object_key", sa.String(length=1024), nullable=False),
        sa.Column("tsa_token", sa.LargeBinary(), nullable=True),
        sa.Column("first_message_id", sa.String(length=64), nullable=False),
        sa.Column("last_message_id", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_index(
        op.f("ix_sealed_batches_last_message_id"),
        "sealed_batches",
        ["last_message_id"],
        unique=False,
    )
    op.create_index(op.f("ix_sealed_batches_org_id"), "sealed_batches", ["org_id"], unique=False)
    op.create_index(
        op.f("ix_sealed_batches_source_id"), "sealed_batches", ["source_id"], unique=False
    )
    op.create_table(
        "structured_artifacts",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("case_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("parser", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=True),
        sa.Column("container_sha256", sa.String(length=64), nullable=True),
        sa.Column("record_index", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("artifact_id"),
    )
    op.create_index(
        op.f("ix_structured_artifacts_case_id"), "structured_artifacts", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_structured_artifacts_evidence_id"),
        "structured_artifacts",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_structured_artifacts_kind"), "structured_artifacts", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_structured_artifacts_org_id"), "structured_artifacts", ["org_id"], unique=False
    )
    op.create_table(
        "yara_rule_pack_published",
        sa.Column("pack_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pack_id"),
    )
    op.create_index(
        op.f("ix_yara_rule_pack_published_org_id"),
        "yara_rule_pack_published",
        ["org_id"],
        unique=False,
    )
    op.create_table(
        "yara_rule_pack_versions",
        sa.Column("pack_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("source_tier", sa.String(length=32), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pack_id", "version", name="pk_yara_rule_pack_versions"),
    )
    op.create_index(
        op.f("ix_yara_rule_pack_versions_org_id"),
        "yara_rule_pack_versions",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_yara_rule_pack_versions_pack_id"),
        "yara_rule_pack_versions",
        ["pack_id"],
        unique=False,
    )
    op.create_table(
        "yara_rule_packs",
        sa.Column("pack_id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pack_id"),
        sa.UniqueConstraint("org_id", "name", name="uq_yara_rule_packs_org_name"),
    )
    op.create_index(op.f("ix_yara_rule_packs_org_id"), "yara_rule_packs", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_yara_rule_packs_org_id"), table_name="yara_rule_packs")
    op.drop_table("yara_rule_packs")
    op.drop_index(op.f("ix_yara_rule_pack_versions_pack_id"), table_name="yara_rule_pack_versions")
    op.drop_index(op.f("ix_yara_rule_pack_versions_org_id"), table_name="yara_rule_pack_versions")
    op.drop_table("yara_rule_pack_versions")
    op.drop_index(op.f("ix_yara_rule_pack_published_org_id"), table_name="yara_rule_pack_published")
    op.drop_table("yara_rule_pack_published")
    op.drop_index(op.f("ix_structured_artifacts_org_id"), table_name="structured_artifacts")
    op.drop_index(op.f("ix_structured_artifacts_kind"), table_name="structured_artifacts")
    op.drop_index(op.f("ix_structured_artifacts_evidence_id"), table_name="structured_artifacts")
    op.drop_index(op.f("ix_structured_artifacts_case_id"), table_name="structured_artifacts")
    op.drop_table("structured_artifacts")
    op.drop_index(op.f("ix_sealed_batches_source_id"), table_name="sealed_batches")
    op.drop_index(op.f("ix_sealed_batches_org_id"), table_name="sealed_batches")
    op.drop_index(op.f("ix_sealed_batches_last_message_id"), table_name="sealed_batches")
    op.drop_table("sealed_batches")
    op.drop_index(op.f("ix_rule_packs_org_id"), table_name="rule_packs")
    op.drop_table("rule_packs")
    op.drop_index(op.f("ix_rule_pack_versions_pack_id"), table_name="rule_pack_versions")
    op.drop_index(op.f("ix_rule_pack_versions_org_id"), table_name="rule_pack_versions")
    op.drop_table("rule_pack_versions")
    op.drop_index(op.f("ix_published_custom_rules_org_id"), table_name="published_custom_rules")
    op.drop_table("published_custom_rules")
    op.drop_table("org_quotas")
    op.drop_index(op.f("ix_ioc_feeds_org_id"), table_name="ioc_feeds")
    op.drop_table("ioc_feeds")
    op.drop_index(op.f("ix_ioc_feed_versions_org_id"), table_name="ioc_feed_versions")
    op.drop_index(op.f("ix_ioc_feed_versions_feed_id"), table_name="ioc_feed_versions")
    op.drop_table("ioc_feed_versions")
    op.drop_index(
        op.f("ix_ioc_feed_current_indicators_feed_id"), table_name="ioc_feed_current_indicators"
    )
    op.drop_index("ix_ioc_current_match", table_name="ioc_feed_current_indicators")
    op.drop_table("ioc_feed_current_indicators")
    op.drop_table("integration_source_cursors")
    op.drop_index(op.f("ix_evidence_org_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_case_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_detections_org_id"), table_name="detections")
    op.drop_index(op.f("ix_detections_case_id"), table_name="detections")
    op.drop_table("detections")
    op.drop_index(op.f("ix_detection_correlations_org_id"), table_name="detection_correlations")
    op.drop_index(
        op.f("ix_detection_correlations_detection_id_b"), table_name="detection_correlations"
    )
    op.drop_index(
        op.f("ix_detection_correlations_detection_id_a"), table_name="detection_correlations"
    )
    op.drop_table("detection_correlations")
    op.drop_index(op.f("ix_dead_letter_events_source_id"), table_name="dead_letter_events")
    op.drop_index(op.f("ix_dead_letter_events_org_id"), table_name="dead_letter_events")
    op.drop_index(op.f("ix_dead_letter_events_batch_id"), table_name="dead_letter_events")
    op.drop_table("dead_letter_events")
    op.drop_index(op.f("ix_cases_org_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_evidence_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_case_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_audit_anchor_org_id"), table_name="audit_anchor")
    op.drop_index(op.f("ix_audit_anchor_anchor_date"), table_name="audit_anchor")
    op.drop_table("audit_anchor")
    op.drop_index(op.f("ix_assets_org_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
