apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kronos.fullname" . }}-config
  namespace: kronos
  labels:
    {{- include "kronos.labels" . | nindent 4 }}
data:
  opensearch-url: {{ .Values.opensearch.url | quote }}
  opensearch-dashboards-url: {{ .Values.opensearch.dashboardsUrl | quote }}
  keycloak-url: {{ .Values.keycloak.url | quote }}
  keycloak-realm: {{ .Values.keycloak.realm | quote }}
  minio-endpoint: {{ .Values.minio.endpoint | quote }}
  vault-addr: {{ .Values.vault.addr | quote }}
