apiVersion: v1
kind: Namespace
metadata:
  name: kronos
  labels:
    app.kubernetes.io/name: kronos
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
