{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kronos.fullname" . }}-app-to-data
  namespace: kronos
  labels:
    {{- include "kronos.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/zone: data
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/zone: app
      ports:
        - protocol: TCP
          port: 5432   # PostgreSQL
        - protocol: TCP
          port: 6379   # Redis
        - protocol: TCP
          port: 9000   # MinIO API
        - protocol: TCP
          port: 9200   # OpenSearch
        - protocol: TCP
          port: 8200   # Vault
        - protocol: TCP
          port: 7373   # KES
        - protocol: TCP
          port: 8080   # Keycloak
        - protocol: TCP
          port: 318    # TSA
{{- end }}
