#!/bin/sh
# Runs once via /docker-entrypoint-initdb.d on first boot of the primary.
#
# Real, confirmed finding (postgresql.org/docs/16/auth-pg-hba-conf.html):
# the pg_hba.conf `database` field value `all` does NOT match physical
# replication connections -- `replication` is a distinct value. The
# official postgres:16-alpine image's own docker-entrypoint.sh only ever
# appends `host all all all $POSTGRES_HOST_AUTH_METHOD` (this file's own
# `host all all all scram-sha-256`, generated by
# POSTGRES_PASSWORD_FILE-driven default auth), which does not cover
# replication connections. Without this explicit entry the replica's
# pg_basebackup/streaming connection is rejected with "no pg_hba.conf
# entry for replication connection" -- reproduced and fixed in
# poc/postgres_replication/ before this file was written (see that PoC's
# README "real finding #1").
#
# Address scope matches the existing `host all all all scram-sha-256` line
# right above this one in the generated pg_hba.conf (both rely on Postgres
# only being reachable from the compose-internal Docker network in this
# deployment topology, not on a tighter pg_hba CIDR) -- not weakening or
# strengthening the file's existing security posture, just extending the
# same posture to cover the one new connection type replication needs.
set -e
echo "host replication replicator all scram-sha-256" >> "$PGDATA/pg_hba.conf"
