apiVersion: v1
kind: Service
metadata:
  name: {{ include "kronos.fullname" . }}-nginx
  namespace: kronos
  labels:
    {{- include "kronos.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "kronos.nginx.selectorLabels" . | nindent 4 }}
